troiswa_bug_homepage:
    path: /
    defaults: { _controller: TroiswaBugBundle:DefaultController:index }


    troiswa_bug_page:
        path:/page
        defaults: { _controller: TroiswaBugBundle:Default:custom }
